apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: your-registry/payment-service:latest
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__Db
            valueFrom:
              secretKeyRef:
                name: payment-secrets
                key: db
          - name: RabbitMq__Host
            value: rabbitmq.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
